name: Build and Test
on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
