name: OKR Server
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false
      - name: Clone Sourcecode
        uses: actions/checkout@v4
      - name: Checkout to server codebase
        run: cd OKR-App/okr-nest
      - name: Install Dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build --if-present
      - name: Test
        run: npm test
